// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2nxRbsrzc8I0ecfvL0fWTFpqZvdPg2m0',
    appId: '1:518285855054:android:c6df981b8c102483d5b61f',
    messagingSenderId: '518285855054',
    projectId: 'neverland-ab55b',
    storageBucket: 'neverland-ab55b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0cFCEyCFSTBtYgnveU8oGeYJHowSJZhs',
    appId: '1:518285855054:ios:f826fe32bbd5b270d5b61f',
    messagingSenderId: '518285855054',
    projectId: 'neverland-ab55b',
    storageBucket: 'neverland-ab55b.firebasestorage.app',
    androidClientId: '518285855054-rjtgih49d2jh6uvf71j7g91339cs9n0v.apps.googleusercontent.com',
    iosClientId: '518285855054-j3pedjgjstjjgubt1hg8u38hcs13uea2.apps.googleusercontent.com',
    iosBundleId: 'com.example.neverlandFlutter',
  );
}
